version: '3.8'
services:
app:
build: .
ports:
- '3000:3000'
env_file: .env
depends_on:
- postgres
postgres:
image: postgres:16
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: meuapp
volumes:
- pgdata:/var/lib/postgresql/data
volumes:
pgdata: